os:
  - linux
  - osx

language: node_js

services:
  - postgres

node_js:
  - "8.11.4"
  - "10.9.0"

before_install:
  - npm install -g pm2

before_script:
  - yarn

script:
  - yarn clean
  - yarn build
  - yarn start:prod
  - yarn test
