os:
  - linux

language: node_js

services:
  - postgres

node_js:
  - node
  - "10.9.0"

before_script:
  - yarn

script:
  - yarn clean
  - yarn build
  - yarn start:prod &
  - yarn test

# after_script:
#   - node kill

env:
  global:
    - CI_NODE_TOTAL=2
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1