os:
  - linux
  - osx

language: node_js

services:
  - postgres

node_js:
  - node
  - "10.9.0"

install:
  yarn

script:
  - yarn clean
  - yarn build
  - yarn start:prod
  - yarn test

env:
  global:
    - CI_NODE_TOTAL=2
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1